

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:${COMMON_PASS}@db:3306/ecommerce?schema=public
    depends_on:
      - db
    # is's called docker bind mount
    volumes:
      - .:/usr/src/app

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${COMMON_PASS}
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8088:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${COMMON_PASS}
    depends_on:
      - db
      
# is's called docker volume
volumes:
  db_data:
